rbac:
  enabled: true
resources:
  namespace: newmysql
  rbacName: mysql-resources
hooks:
  firstinstallPriority: pre-install
  firstupgradePriority: pre-upgrade
  lastinstallPriority: post-install
  lastupgradePriority: post-upgrade
imagepullCredentials:
  secretName: dockerhub
  registry: https://index.docker.io/v1/
  username: avaskumar
  password: ARfit@247
operator:
  global: false
  register_crd: true
  image:
    repository: avashkumar/new-mysql-operator
    tag: 0.3.0
    pullPolicy: IfNotPresent
innodb:
  clusterName: mysql-innodb
  replicas: 1   ### 3
  image:
    repository: avashkumar/mysql-innodb
    tag: 8.0.17
  rootUser:
    secretName: root-password
    password: foobar
  configMycnf: innodb-mycnf
  claimName:
    data: pvcdata
    backup: pvcbackup
  storageclass: my-storageclass   ### ibmc-file-retain-gold
  pvAccess: ReadWriteMany
  storagesize: 1Gi   ### 20Gi
agent:
  image:
    repository: avashkumar/new-mysql-agent
    tag: latest
router:
  replicas: 1   ### 3
  image:
    repository: avashkumar/mysql-router
    tag: 8.0.19
  serviceType: NodePort

 
